zoom issue +other errors
1.When running from github I am getting this error when I open the console log : TypeError: map.getzoom is not a function
2.It looks great that the walk now comes up when you hover over with a mouse. can this be done too with mobile but instead of hover do like a slide or hold down
3.When you click into a walk or park first this is great this should be the max zoom out but when you zoom in a little it zooms in to the max zoom out and it is too close to the map the max zoom out needs to be when you click into the walk first
4.Can I have the same PNG used for the icon as the icon on the website tab
5.Can you add a search bar before Incline and Length, this will be used to search for walk names/park names. This search bar should be before the incline bar ON THE LEFT.
6.Can you put the two final field boxes on top of eachother rather than side to side
1. The zoom function is still working incorrectly I think it may be the setmaxbounds that might be causing the errors. I click on any walk or park here is fine this is exactly what the max bounds or max zoom should be but for some reason when I zoom in a little it sets a new smaller max bounds or max zoom is there any way to set a bigger peramiter or not zoom in as much. How is it defined can you explain the code
2. I want the search bar to be in the top middle of the screan on mobile in between filters and the icon at the top of the screan
3.remove the white border from either the top of the table or bottom of the top bar as there is a white line there